[package]
name = "submillisecond-live-view"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
hmac = { version = "0.12.1", features = ["std"] }
itertools = "0.10"
jwt = "0.16.0"
lunatic = "0.11.4"
lunatic-log = "0.2"
once_cell = "1.14"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.6"
submillisecond = { version = "0.2.0-beta0", features = [
  "cookies",
  "websocket",
] }
tera = { git = "https://github.com/tqwewe/tera", branch = "live-view" }
thiserror = "1.0"
tungstenite = "0.17"
