[package]
name = "subview"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
# lunatic = "^0.11.1"
lunatic = { path = "../lunatic-rs" }
# lunatic-log = "0.2"
lunatic-log = { path = "../logger-rs" }
once_cell = "1.14"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
submillisecond = { path = "../submillisecond", features = [
  "cookies",
  "websocket",
] }
# submillisecond = { git = "https://github.com/lunatic-solutions/submillisecond", branch = "websocket-captures", features = [
#   "cookies",
#   "websocket",
# ] }
# tera = { path = "./tera" }
tera = { git = "https://github.com/tqwewe/tera", branch = "user-defined" }
thiserror = "1.0"
tungstenite = "0.17"
