[package]
name = "submillisecond-live-view"
version = "0.1.0"
edition = "2021"


[dependencies]
base64 = "0.13"
const-random = "0.1"
hmac = { version = "0.12.1", features = ["std"] }
itertools = "0.10"
jwt = "0.16.0"
lunatic = "0.11.4"
lunatic-log = "0.2"
maud = { path = "./crates/maud/maud" }
polonius-the-crab = "0.3"
pretty_assertions = "1.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.10"
sha2 = "0.10.6"
slotmap = "1.0"
submillisecond = { version = "0.2.0-beta0", features = [
  "cookies",
  "websocket",
] }
# tera = { git = "https://github.com/tqwewe/tera", branch = "live-view" }
tera = { path = "../../Keats/tera" }
thiserror = "1.0"
tungstenite = "0.17"

[dev-dependencies]
uuid = { version = "1.2", features = ["serde", "v4"] }
